-- MySQL Script generated by MySQL Workbench
-- 03/16/16 21:48:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`chat_Nation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`chat_Nation` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '国家名字',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`chat_Province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`chat_Province` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '省份名称',
  `nationId` INT NULL COMMENT '外键  所属国家id',
  PRIMARY KEY (`id`),
  INDEX `nationId_idx` (`nationId` ASC),
  CONSTRAINT `nationId1`
    FOREIGN KEY (`nationId`)
    REFERENCES `test`.`chat_Nation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`chat_City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`chat_City` (
  `id` INT NOT NULL,
  `provinceId` INT NULL COMMENT '省份id',
  `chat_Citycol` VARCHAR(45) NULL,
  `chat_Citycol1` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `nationId_idx` (`provinceId` ASC),
  CONSTRAINT `nationId`
    FOREIGN KEY (`provinceId`)
    REFERENCES `test`.`chat_Province` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`chat_friendshipPolicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`chat_friendshipPolicy` (
  `id` INT NOT NULL,
  `friendshipPolicy` VARCHAR(45) NULL COMMENT '好友添加方式 ',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`chat_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`chat_user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `username` VARCHAR(25) NOT NULL COMMENT '用户名',
  `password` VARCHAR(10) NOT NULL COMMENT '密码',
  `moto` VARCHAR(45) NULL COMMENT '个性签名',
  `sex` BIT NULL DEFAULT 0 COMMENT '性别',
  `birthday` VARCHAR(20) NULL COMMENT '生日',
  `telephone` VARCHAR(20) NULL COMMENT '电话号码',
  `email` VARCHAR(50) NULL,
  `imgSrc` VARCHAR(100) NULL COMMENT '头像图片地址',
  `age` INT NULL DEFAULT 0 COMMENT '年龄',
  `bloodType` VARCHAR(2) NULL COMMENT '血型',
  `schoolTag` VARCHAR(45) NULL COMMENT '毕业学校',
  `vocation` VARCHAR(45) NULL COMMENT '职业',
  `cityId` INT NULL COMMENT '城市 外键',
  `friendshipPolicyId` INT NULL COMMENT '好友策略  外键',
  `userStateId` INT NULL COMMENT '用户状态 外键',
  PRIMARY KEY (`id`),
  INDEX `cityId_idx` (`cityId` ASC),
  INDEX `friendshipPolicyId_idx` (`friendshipPolicyId` ASC),
  CONSTRAINT `cityId`
    FOREIGN KEY (`cityId`)
    REFERENCES `test`.`chat_City` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `friendshipPolicyId`
    FOREIGN KEY (`friendshipPolicyId`)
    REFERENCES `test`.`chat_friendshipPolicy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`chat_friendType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`chat_friendType` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '类型名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`chat_friendGroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`chat_friendGroups` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `userId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`userId` ASC),
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `test`.`chat_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`chat_friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`chat_friends` (
  `userId` INT NOT NULL,
  `friendId` INT NOT NULL,
  `fName` VARCHAR(45) NULL COMMENT '好友备注名称',
  `friendTypeId` INT NULL COMMENT '好友类型 外键',
  `friendGroupsId` INT NULL,
  INDEX `userId_idx` (`userId` ASC),
  INDEX `friendGroupsId _idx` (`friendGroupsId` ASC),
  INDEX `friendTypeId_idx` (`friendTypeId` ASC),
  INDEX `friendId_idx` (`friendId` ASC),
  PRIMARY KEY (`userId`, `friendId`),
  CONSTRAINT `friendTypeId1`
    FOREIGN KEY (`friendTypeId`)
    REFERENCES `test`.`chat_friendType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `friendGroupsId 1`
    FOREIGN KEY (`friendGroupsId`)
    REFERENCES `test`.`chat_friendGroups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userId1`
    FOREIGN KEY (`userId`)
    REFERENCES `test`.`chat_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `friendId1`
    FOREIGN KEY (`friendId`)
    REFERENCES `test`.`chat_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`chat_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`chat_messages` (
  `id` INT NOT NULL,
  `text` CHAR NULL COMMENT '消息内容',
  `status` BIT NULL DEFAULT 0 COMMENT '接受状态',
  `time` CHAR NULL COMMENT '发送时间',
  `code` INT NULL DEFAULT 0 COMMENT '消息类型',
  `fromUserId` INT NULL COMMENT '发送者id',
  `toUserId` INT NULL COMMENT '接受者id',
  PRIMARY KEY (`id`),
  INDEX `fromUserId_idx` (`fromUserId` ASC),
  INDEX `toUserId_idx` (`toUserId` ASC),
  CONSTRAINT `fromUserId`
    FOREIGN KEY (`fromUserId`)
    REFERENCES `test`.`chat_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `toUserId`
    FOREIGN KEY (`toUserId`)
    REFERENCES `test`.`chat_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
